### ISSUE TITLE
bla

### ISSUE THREAD

**Issue by flomlo** [TheJonny/flag-complex-mcmc#4]
pub fn edge_mut (&mut self, from: Node, to: Node) -> &mut bool{
        if from as usize >= self.nnodes {
            panic!("from out of bounds");
        }
        if to as usize >= self.nnodes {
            panic!("to out of bounds");
        }
        return &mut self.adjmat[(from as usize) * self.nnodes + (to as usize)];
    }

das geht besser

**Comment by TheJonny** [comment]
ist jetzt eh weg
